#theme: jekyll-theme-hacker
theme: jekyll-theme-minimal
title: "Qianhui, gecko"
description: "I'm best known as the innocent lizard from deserts. Trust me."
show_downloads: false 
logo: logo.jpeg
github.is_project_page: true 
